# config.yaml
external_models:
  vae: "madebyollin/sdxl-vae-fp16-fix"
  tokenizer: "openai/clip-vit-large-patch14"
  text_encoder: "openai/clip-vit-large-patch14"
  # TODO: should I also add the torch.float16 torch_dtype to here?

dit:
  input_size: 32
  patch_size: [1, 2, 2] # (t, h, w)
  grid_size: 16  # input_height // patch_height (or weight)
  hidden_size: 1152 # DiT
  in_channels: 4
  cond_dim: 768 # Clip Large
  frequency_embedding_size: 256
  max_period: 10000
  depth: 28
  num_heads: 16
  learn_variance: False
  vae_scale_factor: 0.18215 # SDXL Standard

training:
  lr: 1.0e-4
  weight_decay: 0
  mixed_precision: "bf16" # Best for RTX 3090
  gradient_checkpointing: True
  batch_size: 2  # TODO: To my knowledge unused in the project for now

general:
  wnb_project_name: "hidopinto-1-weizmann-institute-of-science/Image-Diffusion"